### ISSUE TITLE
Update lego with field-deployment changes

### ISSUE THREAD

**Issue by MajikalExplosions** [Gryphon-Robotics-4990/2020#29]
See https://github.com/Gryphon-Robotics-4990/2020/compare/lego...field-deployment

- [ ] Change climb to single talon (CAN 13)
- [ ] Update Oblog version to 3.1.2
- [ ] Make Constants implement Loggable and link from RobotContainer
- [ ] Update CAN Bus and sensor port constants
- [ ] Update drivetrain motor configs
- [ ] Add Compressor
- [ ] Add ClimbBalanceManualCommand
- [ ] Update Climb command control bindings
- [ ] Set default climb command to manual climb balance
- [ ] Update extend and retract climb commands
- [ ] Update ToggleIntakeCommand
- [ ] Reverse climb solenoids
- [ ] Update drivetrain motor configurations
- [ ] Update hopper to use two motors (final decision TBD)
- [ ] Replace Solenoid in IntakeSubsystem with a DoubleSolenoid
- [ ] Make sure nothing that shouldn't be commented out is commented out (for example, the right drivetrain victor)

**Comment by benjamin-antupit** [comment]
I approve

**Comment by MajikalExplosions** [comment]
lego will be managed by @Dat-Boi-Arjun
